package com.aeab13.training


val fruits = listOf(
    "Abiu",
    "Açaí",
    "Acerola",
    "Ackee",
    "African cucumber",
    "Apple",
    "Apricot",
    "Avocado",
    "Banana",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Black sapote",
    "Blueberry",
    "Boysenberry",
    "Breadfruit",
    "Buddha's hand",
    "Cactus pear",
    "Canistel",
    "Cashew",
    "Cempedak",
    "Cherimoya (Custard Apple)",
    "Cherry",
    "Chico fruit",
    "Cloudberry",
    "Coco De Mer",
    "Coconut",
    "Crab apple",
    "Cranberry",
    "Currant",
    "Damson",
    "Date",
    "Dragonfruit",
    "Durian",
    "Egg Fruit",
    "Elderberry",
    "Feijoa",
    "Fig",
    "Finger Lime",
    "Goji berry",
    "Gooseberry",
    "Grape",
    "Raisin",
    "Grapefruit",
    "Grewia asiatica",
    "Guava",
    "Hala Fruit",
    "Honeyberry",
    "Huckleberry",
    "Jabuticaba",
    "Jackfruit",
    "Jambul",
    "Japanese plum",
    "Jostaberry",
    "Jujube",
    "Juniper berry",
    "Kaffir Lime",
    "Kiwano",
    "Kiwifruit",
    "Kumquat",
    "Lemon",
    "Lime",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lulo",
    "Lychee",
    "Magellan Barberry",
    "Mamey Apple",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Marionberry",
    "Cantaloupe",
    "Galia melon",
    "Honeydew",
    "Mouse melon",
    "Musk melon",
    "Watermelon",
    "Miracle fruit",
    "Monstera deliciosa",
    "Mulberry",
    "Nance",
    "Blood orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Pawpaw",
    "Peach",
    "Pear",
    "Persimmon",
    "Plantain",
    "Plum",
    "Prune",
    "Pineapple",
    "Pineberry",
    "Plumcot",
    "Pomegranate",
    "Pomelo",
    "Purple mangosteen",
    "Quince",
    "Raspberry",
    "Salmonberry",
    "Rambutan",
    "Redcurrant",
    "Rose apple",
    "Salal berry",
    "Salak",
    "Satsuma",
    "Shine Muscat or Vitis Vinifera",
    "Sloe or Hawthorn Berry",
    "Soursop",
    "Star apple",
    "Star fruit",
    "Strawberry",
    "Surinam cherry",
    "Tamarillo",
    "Tamarind",
    "Tangelo",
    "Tayberry",
    "Ugli fruit",
    "White currant",
    "White sapote",
    "Yuzu",
)
